<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJr5ebFz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJr5ebFz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJr5ebFz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJr5ebFz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJr5ebFz\App_KernelDevDebugContainer([
    'container.build_hash' => 'Jr5ebFz',
    'container.build_id' => '87f8d919',
    'container.build_time' => 1697010320,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJr5ebFz');
