<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJxXM8VI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJxXM8VI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJxXM8VI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJxXM8VI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJxXM8VI\App_KernelDevDebugContainer([
    'container.build_hash' => 'JxXM8VI',
    'container.build_id' => '7aaf7460',
    'container.build_time' => 1698219766,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJxXM8VI');
