<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFxrAnJa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFxrAnJa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFxrAnJa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFxrAnJa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFxrAnJa\App_KernelDevDebugContainer([
    'container.build_hash' => 'FxrAnJa',
    'container.build_id' => '57015da2',
    'container.build_time' => 1697181363,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFxrAnJa');
